export const tagTypes = {
  auth: 'auth',
  category: 'category',
  product: 'product',
  customer: 'customer',
  productImage: 'productImage',
  order: 'order',
  sale_executive: 'sale_executive',
  pathao: 'pathao',
  courierOrderAssigned: 'courierOrderAssigned',
  pathaoStore: 'pathaoStore',
  expense_category: 'expense_category',
  expense: 'expense',
  income_category: 'income_category',
  income: 'income',
  attendance: 'attendance',
  salary: 'salary',
  summary: 'summary',
  company: 'company',
  stock: 'stock',
  stock_out: 'stock_out',
  brand: 'brand',
  deal: 'deal',
  topRanking: 'topRanking',
  inventory: 'inventory',
  review: 'review',
  account: 'account',
  accountingCategory: 'accountingCategory',
  transaction: 'transaction',
  ledger: 'ledger',
  report: 'report',
  designation: 'designation',
  employee: 'employee',
  courierServiceToken: 'courierServiceToken',
  User: 'User',
  CustomerLevel: 'CustomerLevel',
  CustomerRank: 'CustomerRank',
  orderSource: 'orderSource',
  banner: 'banner',
  Pages: 'Pages',
  Testimonials: 'Testimonials',
  Dashboard: 'Dashboard',
  coupon: 'coupon',
  deliveryCharge: 'deliveryCharge',
  companyInfo: 'companyInfo',
  messageTemplate: 'messageTemplate',
  messageLog: 'messageLog',
  orderPayment: 'orderPayment',
  featuredSection: 'featuredSection',
  featureType: 'featureType',
  trendingSearch: 'trendingSearch',
  subscriber: 'subscriber',
  gallery: 'gallery',
  blog: 'blog',
  blogCategory: 'blogCategory',
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.category,
  tagTypes.product,
  tagTypes.productImage,
  tagTypes.order,
  tagTypes.sale_executive,
  tagTypes.pathao,
  tagTypes.courierOrderAssigned,
  tagTypes.pathaoStore,
  tagTypes.expense_category,
  tagTypes.expense,
  tagTypes.income_category,
  tagTypes.income,
  tagTypes.attendance,
  tagTypes.salary,
  tagTypes.summary,
  tagTypes.company,
  tagTypes.stock,
  tagTypes.stock_out,
  tagTypes.brand,
  tagTypes.deal,
  tagTypes.topRanking,
  tagTypes.inventory,
  tagTypes.review,
  tagTypes.account,
  tagTypes.accountingCategory,
  tagTypes.transaction,
  tagTypes.ledger,
  tagTypes.report,
  tagTypes.designation,
  tagTypes.employee,
  tagTypes.courierServiceToken,
  tagTypes.User,
  tagTypes.CustomerLevel,
  tagTypes.CustomerRank,
  tagTypes.orderSource,
  tagTypes.banner,
  tagTypes.Pages,
  tagTypes.Testimonials,
  tagTypes.Dashboard,
  tagTypes.coupon,
  tagTypes.deliveryCharge,
  tagTypes.companyInfo,
  tagTypes.messageTemplate,
  tagTypes.messageLog,
  tagTypes.orderPayment,
  tagTypes.featuredSection,
  tagTypes.featureType,
  tagTypes.trendingSearch,
  tagTypes.subscriber,
  tagTypes.gallery,
  tagTypes.blogCategory,
  tagTypes.blog,
];
